apiVersion: v1
kind: Secret
metadata:
  name: {{ template "redis.fullname" . }}
  labels:
    app: {{ template "redis.fullname" . }}
    release: "{{ .Release.Name }}"
type: Opaque
data:
  redis-password: {{ include "redis.password" . | b64enc | quote }}