apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "redis.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "redis.labels" . | nindent 8 }}
  template:
    metadata:
      labels:
        {{- include "redis.labels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        resources:
          {{- toYaml .Values.resources | nindent 12 }} 
        ports:
        - name: {{ include "redis.fullname" . }}
          containerPort: 6379
          protocol: TCP
        volumeMounts:
        - name: data
          mountPath: /data
        env:
        - name: {{ include "redis.fullname" . }}
          valueFrom:
            secretKeyRef:
              name: {{ include "redis.fullname" . }}
              key: redis-password                                    
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        {{- include "redis.labels" . | nindent 8 }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
