apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.headless.name }}
  labels:
    app: cassandra
spec:
  type: ClusterIP
  ports:
  - name: {{ .Values.service.headless.name }}
    port: {{ .Values.service.headless.port }}
    targetPort: {{ .Values.service.headless.port }}