apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    app: {{ include "postgresql.fullname" . }}
spec:
  type: ClusterIP
  ports:
  - name: {{ include "postgresql.fullname" . }}
    port: {{ .Values.postgresql.port }}
    targetPort: {{ .Values.postgresql.port }}
