apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}-headless
  labels:
    app: {{ include "postgresql.fullname" . }}
spec:
  clusterIP: None
  selector:
    app: {{ include "postgresql.fullname" . }}
  ports:
    - name: postgresql
      port: {{ .Values.postgresql.port }}
      protocol: TCP
