apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "postgresql.fullname" . }}
spec:
  serviceName: {{ include "postgresql.fullname" . }}-headless
  replicas: {{ .Values.postgresql.replicas }}
  selector:
    matchLabels:
      app: {{ include "postgresql.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "postgresql.fullname" . }}
    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgresql.image }}
          imagePullPolicy: {{ .Values.postgresql.imagePullPolicy }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password }}
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.database }}
          ports:
            - name: postgresql
              containerPort: {{ .Values.postgresql.port }}
          volumeMounts:
            - name: data-mydatabase1
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-mydatabase1
          persistentVolumeClaim:
            claimName: {{ include "postgresql.fullname" . }}-data-mydatabase1           
  volumeClaimTemplates:
    - metadata:
        name: data-mydatabase1
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.postgresql.storage.size }}
