replicaCount: 3

image:
  repository: redis
  tag: 6.0.9

persistence:
  enabled: true
  size: 1Gi

resources:
  limits:
    cpu: 100m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 256Mi

redis:
  password: ""

## Redis config file
##
configmap: |-
#  Redis configuration file

